sptk_ver=3.11
festival_ver=2.5.0
festival_short_ver=2.5
hts_ver=2.3
htk_ver=3.4.1
hts_engine_ver=1.10
gcc_festival=gcc
copy_script=../prozodija/src/groovy/src/scripts/copy/CopyDataToHts.groovy
prepared_data_dir=../prozodija/prepareData/tmp
USEGV=0

